### ISSUE TITLE
Feature: S3 핸들링 관련 로직 구현

### ISSUE THREAD

**Issue by lcomment** [najasin/na-jasin-be#8]
## Description

> S3에 파일을 업로드하거나 삭제하는 등의 로직을 구현한다.

## To-do

- [ ] S3 연동
- [ ] S3 핸들러 구현

**Comment by adoo24** [comment]
admin 패널을 만들어서 구현하실 생각인가요?

**Comment by lcomment** [comment]
@adoo24 말씀하신 admin 패널이 정확히 어떤걸 의미하는거죠? 저는 S3에대한 access를 가진 IAM을 발급해서 서버와 연동하고,  업로드나 삭제 기능을 가진 Bean을 구현하여, service layer에 주입하는 로직을 생각했습니다.

**Comment by adoo24** [comment]
![image](https://github.com/najasin/na-jasin-be/assets/99449600/38416dd1-c8ff-4e2e-8e5d-7cd7055d3c39)

관리자 권한을 가진 유저가 캐릭터셋이나 캐릭터 파트 사진을 올릴 수 있는 페이지를 가정하셔서 해당 로직을 만드셨는지 여쭤봤습니다. 맞나요?

**Comment by lcomment** [comment]
아뇨. 슬랙에서 랜더링 속도를 높이기 위해 파트별 조합이 아닌 완성된 캐릭터를 저장하자고 말씀해주셔서, 관리자가 아닌 일반 유저가 보내는 multipart 요청에서 이미지를 업로드 하는 로직을 작성할 계획입니다.

**Comment by adoo24** [comment]
이해했습니다 감사합니다!

**Comment by lcomment** [comment]
근데 다시 조합하는거로 바꼈네요 ㅋㅋㅋ 이슈 클로즈하겠슴다 ㅎㅎㅎ,,
